to predict it will rain or not

In [59]:
#Do data ingestion
import pandas as pd
df = pd.read_csv('/content/weatherAUS.csv')
df.head()

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Humidity9am,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RainTomorrow
0,2008-12-01,Albury,13.4,22.9,0.6,NaN,NaN,W,44.0,W,...,71.0,22.0,1007.7,1007.1,8.0,NaN,16.9,21.8,No,No
1,2008-12-02,Albury,7.4,25.1,0.0,NaN,NaN,WNW,44.0,NNW,...,44.0,25.0,1010.6,1007.8,NaN,NaN,17.2,24.3,No,No
2,2008-12-03,Albury,12.9,25.7,0.0,NaN,NaN,WSW,46.0,W,...,38.0,30.0,1007.6,1008.7,NaN,2.0,21.0,23.2,No,No
3,2008-12-04,Albury,9.2,28.0,0.0,NaN,NaN,NE,24.0,SE,...,45.0,16.0,1017.6,1012.8,NaN,NaN,18.1,26.5,No,No
4,2008-12-05,Albury,17.5,32.3,1.0,NaN,NaN,W,41.0,ENE,...,82.0,33.0,1010.8,1006.0,7.0,8.0,17.8,29.7,No,No

#preprocessing

In [60]:
#Handling missing values
df.isnull().sum()

Date                 0
Location             0
MinTemp           1485
MaxTemp           1261
Rainfall          3261
Evaporation      62790
Sunshine         69835
WindGustDir      10326
WindGustSpeed    10263
WindDir9am       10566
WindDir3pm        4228
WindSpeed9am      1767
WindSpeed3pm      3062
Humidity9am       2654
Humidity3pm       4507
Pressure9am      15065
Pressure3pm      15028
Cloud9am         55888
Cloud3pm         59358
Temp9am           1767
Temp3pm           3609
RainToday         3261
RainTomorrow      3267
dtype: int64

In [61]:
df = df.fillna(df.isnull().sum())

In [62]:
pd.get_dummies(df, columns=['RainToday','RainTomorrow'])

,Date,Location,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,...,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday_3261,RainToday_No,RainToday_Yes,RainTomorrow_3267,RainTomorrow_No,RainTomorrow_Yes
0,2008-12-01,Albury,13.4,22.9,0.6,62790.0,69835.0,W,44.0,W,...,8.0,59358.0,16.9,21.8,0,1,0,0,1,0
1,2008-12-02,Albury,7.4,25.1,0.0,62790.0,69835.0,WNW,44.0,NNW,...,55888.0,59358.0,17.2,24.3,0,1,0,0,1,0
2,2008-12-03,Albury,12.9,25.7,0.0,62790.0,69835.0,WSW,46.0,W,...,55888.0,2.0,21.0,23.2,0,1,0,0,1,0
3,2008-12-04,Albury,9.2,28.0,0.0,62790.0,69835.0,NE,24.0,SE,...,55888.0,59358.0,18.1,26.5,0,1,0,0,1,0
4,2008-12-05,Albury,17.5,32.3,1.0,62790.0,69835.0,W,41.0,ENE,...,7.0,8.0,17.8,29.7,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145455,2017-06-21,Uluru,2.8,23.4,0.0,62790.0,69835.0,E,31.0,SE,...,55888.0,59358.0,10.1,22.4,0,1,0,0,1,0
145456,2017-06-22,Uluru,3.6,25.3,0.0,62790.0,69835.0,NNW,22.0,SE,...,55888.0,59358.0,10.9,24.5,0,1,0,0,1,0
145457,2017-06-23,Uluru,5.4,26.9,0.0,62790.0,69835.0,N,37.0,SE,...,55888.0,59358.0,12.5,26.1,0,1,0,0,1,0
145458,2017-06-24,Uluru,7.8,27.0,0.0,62790.0,69835.0,SE,28.0,SSE,...,3.0,2.0,15.1,26.0,0,1,0,0,1,0
145459,2017-06-25,Uluru,14.9,1261.0,0.0,62790.0,69835.0,10326,10263.0,ESE,...,8.0,8.0,15.0,20.9,0,1,0,1,0,0

In [63]:
mapping_dict = {"Yes": 1,"No":0,"NaN":0,"Na":0}
df['RainToday'] = df['RainToday'].map(mapping_dict)
df['RainTomorrow'] = df['RainTomorrow'].map(mapping_dict)

In [64]:
#Feature scaling/normalization
df['RainToday'] = (df['RainToday'] - df['RainToday'].mean()) / df['RainToday'].std()

In [65]:
df['RainToday'] = (df['RainToday'] - df['RainToday'].min()) / (df['RainToday'].max() - df['RainToday'].min())

In [66]:
df['RainTomorrow'] = (df['RainTomorrow'] - df['RainTomorrow'].mean()) / df['RainTomorrow'].std()

In [67]:
df['RainTomorrow'] = (df['RainTomorrow'] - df['RainTomorrow'].min()) / (df['RainTomorrow'].max() - df['RainTomorrow'].min())

ML model

In [68]:
#logistic regression 
# libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

In [69]:
X = df[['RainToday','RainTomorrow']].values
y = df['Rainfall'].values
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [70]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Load the dataset into a pandas DataFrame

# Split the dataset into features (X) and target variable (y)
X = df.drop('RainTomorrow', axis=1)  # Features (all columns except the target variable)
y = df['RainTomorrow']  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Print the shapes of the resulting datasets
print("Shape of X_train:", X_train.shape)
print("Shape of X_test:", X_test.shape)
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)

Shape of X_train: (116368, 22)
Shape of X_test: (29092, 22)
Shape of y_train: (116368,)
Shape of y_test: (29092,)

In [71]:
print(X_test.shape)
print(X_train.shape)

(29092, 22)
(116368, 22)

In [38]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)   #data leakage

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_data.py:473: RuntimeWarning: All-NaN slice encountered
  data_min = np.nanmin(X, axis=0)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_data.py:474: RuntimeWarning: All-NaN slice encountered
  data_max = np.nanmax(X, axis=0)